version: '3.8'

services:
  trading-bot:
    # 定义服务的名称
    container_name: binance_event_trader
    
    # 构建指令
    # context: . 表示使用当前目录下的Dockerfile进行构建
    build:
      context: .
      dockerfile: Dockerfile
      
    # 环境变量文件
    # Docker Compose会自动寻找项目根目录下的 .env 文件，并将其中的变量注入到容器中
    # 这使得API密钥等敏感信息与代码和镜像分离，非常安全
    env_file:
      - .env
      
    # 新增: 环境变量, 用于区分运行环境
    # 这个变量将作为信号旗，让start.py知道自己是在非交互式的Docker环境中运行
    environment:
      - EXECUTION_MODE=docker
      
    # 数据卷挂载 (核心部分)
    # 这部分实现了数据的持久化，确保容器重启或重建后数据不丢失
    volumes:
      # 将宿主机的 ./logs 目录挂载到容器的 /app/logs 目录
      # 这样，所有程序日志都会被保存在服务器上，方便排查问题
      - ./logs:/app/logs
      
      # 将宿主机的 ./data 目录挂载到容器的 /app/data 目录
      # 这里就是为SQLite数据库准备的。当程序在/app/data下创建数据库文件时，
      # 它会真实地被存储在服务器的./data目录中。
      - ./data:/app/data
      
    # 重启策略
    # unless-stopped: 除非手动停止，否则容器总是在退出后自动重启，确保服务高可用
    restart: unless-stopped 